### PR TITLE
test(complex-objects): Add tests for complex objects upload

### LINKED ISSUE #161: Multiple file upload does not work
I have a types and mutation `createProduct`

```graphql
input CreateProductInput {
	categoryIds: [ID!]!
	description: String
	id: ID!
	images: [S3ObjectInput!]!
	slug: String!
	title: String!
}

type Mutation {
	createProduct(input: CreateProductInput!): Product}
}
```

But when I call the mutation with multiple files, only the first file is being uploaded.

Is there a plan on implementation of multiple files upload?

### PR DESCRIPTION
**Pull request by manueliglesias**
*Issue #, if available:*
Fixes #161 
Fixes: #183 

Closes #179 
Closes #204 

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: packages/aws-appsync/src/link/complex-object-link.ts [hunk 1]
```diff
@@ -83,39 +86,44 @@ const complexObjectFields = [
...
+    const _findInObject = (obj, path = '', acc = {}) => {
+        if (!obj) {
+            return acc;
+        }
 
-                    return isOfType;
-                });
+        if (testFn(obj)) {
+            acc[path] = { ...obj };
+            delete obj.mimeType;
```
Comment (elorzafe) [inline packages/aws-appsync/src/link/complex-object-link.ts]: Why you need to delete those?

Comment (manueliglesias) [reply packages/aws-appsync/src/link/complex-object-link.ts]: Because once we upload to S3, there's no need to send the file contents and mimeType to AppSync too
